# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
VAGRANT_DOTFILE_PATH = /darwin/ =~ RUBY_PLATFORM ? ".vagrant" : ".vagrant-sub"
currpath = ENV['VAGRANT_DOTFILE_PATH'] || '.vagrant'
if currpath != VAGRANT_DOTFILE_PATH
  ENV['VAGRANT_DOTFILE_PATH'] = VAGRANT_DOTFILE_PATH
  args = ARGV.join(' ')
  system "vagrant #{args}"
  FileUtils.rm_r(currpath)
  abort 'Finished'
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  settings = {} 
  if /darwin/ =~ RUBY_PLATFORM # macos
    settings[:ipaddr] = "192.168.0.218"
    settings[:port] = 2252
    settings[:workspace_path] = "~/Dropbox/workspace/webstream-framework/"
  else # windows
    settings[:ipaddr] = "192.168.0.219"
    settings[:port] = 2253
    settings[:workspace_path] = "/Users/tanak/Dropbox/workspace/webstream-framework/"
  end

  config.vm.define "webstream-test" do |node|
    node.vm.box = "bento/centos-7.4"
    node.vm.hostname = "webstream-test"
    node.vm.network :public_network, ip: settings[:ipaddr], bridge: "en1: Wi-Fi (AirPort)"
    node.vm.network :forwarded_port, guest: 22, host: settings[:port], id: "ssh"
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 2048]
  end

  config.vm.synced_folder "setup", "/vagrant",
    type: "rsync",
    owner: "vagrant",
    group: "vagrant"

  ["IO", "Container" ,"Log", "Cache", "DI", "Annotation", "Exception", "ClassLoader", "Database"].each do |repository|
      config.vm.synced_folder settings[:workspace_path] + repository, "/workspace/webstream-framework/" + repository,
        type: "rsync",
        owner: "vagrant",
        group: "vagrant",
        rsync__exclude: [".git/", "sandbox/", "vendor/", "composer.lock"]
  end

  config.vm.synced_folder settings[:workspace_path] + "WebStream", "/workspace/webstream-framework/WebStream",
    type: "rsync",
    owner: "vagrant",
    group: "vagrant",
    rsync__exclude: [".git/", "sandbox/", "vendor/", "test/Application/log/", "test/Application/core/"]

  config.vm.synced_folder settings[:workspace_path] + "WebStream/src", "/workspace/webstream-framework/WebStream/test/Application/core",
    type: "rsync",
    owner: "vagrant",
    group: "vagrant"

  config.vm.provision :ansible_local do |ansible|
    ansible.compatibility_mode = '2.0'
    ansible.playbook = "setup.yml"
  end

  config.ssh.pty = true
end
