# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
VAGRANT_DOTFILE_PATH = /darwin/ =~ RUBY_PLATFORM ? ".vagrant" : ".vagrant-sub"
currpath = ENV['VAGRANT_DOTFILE_PATH'] || '.vagrant'
if currpath != VAGRANT_DOTFILE_PATH
  ENV['VAGRANT_DOTFILE_PATH'] = VAGRANT_DOTFILE_PATH
  args = ARGV.join(' ')
  system "vagrant #{args}"
  FileUtils.rm_r(currpath)
  abort 'Finished'
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  settings = {}
  if /darwin/ =~ RUBY_PLATFORM # macos
    settings[:host] = "webstream-test"
    settings[:ipaddr] = "192.168.0.218"
    settings[:workspace_path] = "~/Dropbox/workspace/webstream-framework/"
  else # windows
    settings[:host] = "webstream-test-sub"
    settings[:ipaddr] = "192.168.0.219"
    settings[:workspace_path] = "/mnt/c/Users/tanak/Dropbox/workspace/webstream-framework/"
  end

  config.vm.define settings[:host] do |node|
    node.vm.box = "bento/centos-7.4"
    node.vm.hostname = settings[:host]
    node.vm.network :public_network, ip: settings[:ipaddr], bridge: "en1: Wi-Fi (AirPort)"
    node.vm.network :forwarded_port, guest: 22, host: 2252, id: "ssh"
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 2048]
  end

  config.vm.synced_folder "setup", "/vagrant",
    type: "rsync",
    owner: "vagrant",
    group: "vagrant"

  config.vm.synced_folder settings[:workspace_path] + "Test", "/workspace/webstream-framework/Test",
    type: "rsync",
    owner: "vagrant",
    group: "vagrant",
    rsync__exclude: [".git/", "sandbox/", "vendor/", "TestApp/vendor/", "TestApp/core/", "TestApp/log/"]

  config.vm.synced_folder settings[:workspace_path] + "WebStream", "/workspace/webstream-framework/Test/TestApp/core",
    type: "rsync",
    owner: "vagrant",
    group: "vagrant",
    rsync__exclude: [".git/", "sandbox/"]

  ["IO", "Container" ,"Log", "Cache", "DI", "Annotation", "Exception", "ClassLoader", "Database"].each do |repository|
      config.vm.synced_folder settings[:workspace_path] + repository, "/workspace/webstream-framework/" + repository,
        type: "rsync",
        owner: "vagrant",
        group: "vagrant",
        rsync__exclude: [".git/", "sandbox/", "vendor/"]
  end

  config.vm.provision :ansible_local do |ansible|
    ansible.playbook = "setup.yml"
  end

  config.ssh.pty = true
end
