- name: install sqlite3
  shell: >-
    /usr/bin/wget {{ sqlite_download_url }}{{ sqlite_arvhice_name }} &&
    /usr/bin/unzip {{ sqlite_arvhice_name }} &&
    mv -f sqlite3 /usr/bin/sqlite3
- name: copy sqlfile
  copy: "src={{ sqlite_sqlfile }} dest=/home/vagrant/"
- name: initialize table
  shell: "/usr/bin/sqlite3 /home/vagrant/{{ db_name }}.db < {{ sqlite_sqlfile }}"
- name: database.sqlite.ini settings
  lineinfile: >-
    dest=/var/www/html/webstream-framework/WebStream/core/WebStream/Test/Sample/config/database.sqlite.ini
    regexp='^dbfile'
    line="dbfile = /home/vagrant/{{ db_name }}.db"
    state=present
- name: permission settings
  shell: /usr/bin/chmod -R 777 /home/vagrant
  sudo: yes