- name: copy files
  tags: always
  copy: src="{{ item }}" dest="{{ ansible_env.PWD }}"
  with_items:
    - mysql
    - postgres
    - sqlite
    - webstream
# Database(Mysql/PostgreSQL/Sqlite)
- include: php5.4/docker-run-database.yml
  tags: php5.4
- include: php5.5/docker-run-database.yml
  tags: php5.5
- include: php5.6/docker-run-database.yml
  tags: php5.6
- include: php7.0/docker-run-database.yml
  tags: php7.0
# WebStream
- include: php5.4/docker-run-webstream.yml
  tags: php5.4
- include: php5.5/docker-run-webstream.yml
  tags: php5.5
- include: php5.6/docker-run-webstream.yml
  tags: php5.6
- include: php7.0/docker-run-webstream.yml
  tags: php7.0
