- name: copy ansible files
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'mysql/ansible',     dest: '/home/vagrant/applications/webstream/mysql' }
    - { src: 'postgres/ansible',  dest: '/home/vagrant/applications/webstream/postgres' }
    - { src: 'sqlite/ansible',    dest: '/home/vagrant/applications/webstream/sqlite' }
    - { src: 'webstream/ansible', dest: '/home/vagrant/applications/webstream/webstream' }
# Database(Mysql/PostgreSQL/Sqlite)
- name: docker run (database)
  shell: "{{ item.shell }}"
  with_items:
    - { shell: 'docker run -itd --privileged --volumes-from data_mysql --name webstream-mysql docker/mysql /sbin/init' }
    - { shell: 'docker run -itd --privileged --volumes-from data_postgres --name webstream-postgres docker/postgres /sbin/init' }
    - { shell: 'docker run -itd --privileged --volumes-from data_sqlite --name webstream-sqlite docker/sqlite /sbin/init' }
  sudo: yes
- name: copy files
  copy: src="{{ item }}" dest="{{ ansible_env.PWD }}"
  with_items:
    - mysql
    - postgres
    - sqlite
    - webstream
- name: copy ansible files to container (mysql)
  shell: tar -cv * | sudo docker exec -i webstream-mysql tar x -C /root/ansible chdir=mysql/ansible
- name: copy ansible files to container (postgres)
  shell: tar -cv * | sudo docker exec -i webstream-postgres tar x -C /root/ansible chdir=postgres/ansible
- name: copy ansible files to container (sqlite)
  shell: tar -cv * | sudo docker exec -i webstream-sqlite tar x -C /root/ansible chdir=sqlite/ansible
- name: docker provision (database)
  shell: "{{ item.shell }}"
  with_items:
    - { shell: 'sudo docker exec webstream-mysql ansible-playbook -i "localhost," /root/ansible/settings.yml' }
    - { shell: 'sudo docker exec webstream-postgres ansible-playbook -i "localhost," /root/ansible/settings.yml' }
    - { shell: 'sudo docker exec webstream-sqlite ansible-playbook -i "localhost," /root/ansible/settings.yml' }
  sudo: yes
# WebStream
- name: docker run (webstream)
  shell: docker run -itd -p 80:80 --link webstream-mysql:mysql --link webstream-postgres:postgres --volumes-from webstream-sqlite --privileged --volumes-from data_apache --name webstream docker/php56-apache /sbin/init
  sudo: yes
- name: copy ansible files to container (webstream)
  shell: tar -cv * | sudo docker exec -i webstream tar x -C /root/ansible chdir=applications/webstream/ansible
  sudo: yes
- name: docker provision (webstream)
  shell: docker exec -it webstream ansible-playbook -i "localhost," /root/ansible/settings.yml
  sudo: yes
