- name: copy ansible files
  tags: always
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'mysql/ansible',     dest: '/home/vagrant/applications/webstream/mysql' }
    - { src: 'postgres/ansible',  dest: '/home/vagrant/applications/webstream/postgres' }
    - { src: 'sqlite/ansible',    dest: '/home/vagrant/applications/webstream/sqlite' }
    - { src: 'webstream/ansible', dest: '/home/vagrant/applications/webstream/webstream' }
# Database(Mysql/PostgreSQL/Sqlite)
- include: docker-run-database.yml
  tags: always
# WebStream
- include: docker-run-webstream.yml
  tags: always
