- name: copy ansible files
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'mysql/ansible',     dest: '/home/vagrant/applications/webstream/mysql' }
    - { src: 'postgres/ansible',  dest: '/home/vagrant/applications/webstream/postgres' }
    - { src: 'sqlite/ansible',    dest: '/home/vagrant/applications/webstream/sqlite' }
# Database(Mysql/PostgreSQL/Sqlite)
- name: docker run (database)
  shell: "{{ item.shell }}"
  with_items:
    - { shell: 'docker run -itd --privileged --volumes-from data_mysql --name webstream-mysql docker/mysql /sbin/init' }
    - { shell: 'docker run -itd --privileged --volumes-from data_postgres --name webstream-postgres docker/postgres /sbin/init' }
    - { shell: 'docker run -itd --privileged --volumes-from data_sqlite --name webstream-sqlite docker/sqlite /sbin/init' }
  sudo: yes
- name: copy ansible files to container (mysql)
  shell: tar -cv * | sudo docker exec -i webstream-mysql tar x -C /root/ansible chdir=applications/webstream/mysql/ansible
- name: copy ansible files to container (postgres)
  shell: tar -cv * | sudo docker exec -i webstream-postgres tar x -C /root/ansible chdir=applications/webstream/postgres/ansible
- name: copy ansible files to container (sqlite)
  shell: tar -cv * | sudo docker exec -i webstream-sqlite tar x -C /root/ansible chdir=applications/webstream/sqlite/ansible
- name: docker provision (database)
  shell: "{{ item.shell }}"
  with_items:
    - { shell: 'sudo docker exec -it webstream-mysql ansible-playbook -i "localhost," /root/ansible/settings.yml' }
    - { shell: 'sudo docker exec -it webstream-postgres ansible-playbook -i "localhost," /root/ansible/settings.yml' }
    - { shell: 'sudo docker exec -it webstream-sqlite ansible-playbook -i "localhost," /root/ansible/settings.yml' }
  sudo: yes
