---
# common
db_name: sandbox
wwwroot: /var/www/html

# mysql
mysql_sqlfile: setup.mysql.sql
mysql_sqlfile_timezone: setup-timezone.sql
mysql_userid: mysql
mysql_passwd: mysql

# postgres
postgresql_sqlfile: setup.postgres.sql
postgresql_userid: postgres
postgresql_passwd: postgres

# sqlite
sqlite_sqlfile: setup.sqlite3.sql
