# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # host
  config.vm.define "host" do |node|
    node.vm.box = "chef/centos-6.5"
    node.vm.hostname = "webstream-host"
    node.vm.network :public_network, ip: "192.168.0.202"
  end

  # webstream-test
  config.vm.define "webstream-test" do |node|
    node.vm.box = "chef/centos-6.5"
    node.vm.hostname = "webstream-test"
    node.vm.network :public_network, ip: "192.168.0.205"

    config.vm.provision :ansible do |ansible|
      ansible.playbook = "webstream-test-setup.yml"
      ansible.host_key_checking = false
    end
  end
end
