- name: get WebStream repository
  git: "repo={{ repo_uri }} version={{ branch }} dest={{ test_dir }} update=yes accept_hostkey=yes"
- name: create initial log file
  shell: "/usr/bin/touch {{ test_app_dir }}{{ test_log_path }}/webstream.test.log"
- name: change permission
  file: path="{{ item.path }}" mode="{{ item.mode }}"
  with_items:
    - { path: "{{ test_app_dir }}{{ test_log_path }}", mode: "0777", state: "directory" }
    - { path: "{{ test_app_dir }}{{ test_log_path }}/webstream.test.log", mode: "0777", state: "touch" }
    - { path: "{{ test_app_dir }}{{ test_view_cache_path }}", mode: "0777", state: "directory" }
    - { path: "{{ test_app_dir }}{{ test_static_file_path }}", mode: "0777", state: "directory" }
- name: execute composer (Test)
  composer: "command=install working_dir={{ test_dir }}"
- name: execute composer (TestApp)
  composer: "command=install working_dir={{ test_app_dir }}"
- name: apache force restart
  shell: systemctl restart httpd.service
  sudo: yes
- name: rewrite mysql config file
  lineinfile: >-
    dest='{{ test_app_dir }}/config/{{ item.dest }}'
    regexp='{{ item.regexp }}'
    line='{{ item.line }}'
    state=present
  with_items:
    - dest: 'database.mysql.ini'
      regexp: '^host\s?=.*'
      line: 'host = mysql'
    - dest: 'database.mysql.yml'
      regexp: '^host\s?:.*'
      line: 'host: mysql'
    - dest: 'database.mysql.yaml'
      regexp: '^host\s?:.*'
      line: 'host: mysql'
    - dest: 'database.postgresql.ini'
      regexp: '^host\s?=.*'
      line: 'host = postgres'
    - dest: 'database.sqlite.ini'
      regexp: '^dbfile\s?=.*'
      line: 'dbfile = /mnt/docker/sqlite/sandbox.db'
