# - name: install libselinux-python
#   yum: name=libselinux-python state=latest
# - name: set yum repository
#   yum: name={{ item }}
#   with_items:
#     - https://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
#     - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
#     - http://dev.mysql.com/get/mysql-community-release-el7-5.noarch.rpm
# - name: install git
#   yum: name=git state=latest
# - name: install unzip
#   yum: name=unzip state=latest
# - name: ld-linux.so.2 for sqlite3
#   yum: name=ld-linux.so.2 state=latest
# - name: install locate
#   yum: name=mlocate state=latest
# - name: permission settings
#   shell: /usr/bin/chmod -R 777 /var/log
#   sudo: yes
- name: install packages
  yum: name={{ item }} state=latest
  with_items:
    - epel-release
    - git
    - gcc
    - python-devel
    - libselinux-python
    - docker
- name: restart docker
  service: name=docker state=restarted
- name: force docker container clear
  shell: docker ps -a -q | awk '{if (length($1) > 0) system("sudo docker rm -f " $1)}'
  sudo: yes
- name: copy docker file
  copy: src=Dockerfile dest=/home/vagrant/common/
- name: docker build
  shell: docker build -t docker/base common
  sudo: yes
