- name: install packages
  yum: name={{ item }} state=latest
  with_items:
    - epel-release
    - git
    - gcc
    - python-devel
    - libselinux-python
    - docker
- name: restart docker
  service: name=docker state=restarted
- name: docker container clear
  shell: docker rm -f {{ item }}
  with_items:
    - webstream
    - webstream-mysql
    - webstream-postgres
    - webstream-sqlite
    - data_apache
    - data_mysql
    - data_postgres
    - data_sqlite
  sudo: yes
- name: docker build
  shell: docker build -t docker/base {{ ansible_env.PWD }}/roles/common/files/
  sudo: yes
