- name: install packages
  yum: name={{ item }} state=latest
  with_items:
    - epel-release
    - git
    - gcc
    - python-devel
    - libselinux-python
    - docker
- name: restart docker
  service: name=docker state=restarted
- name: force docker container clear
  shell: docker ps -a -q | awk '{if (length($1) > 0) system("sudo docker rm -f " $1)}'
  sudo: yes
- name: docker build
  shell: docker build -t docker/base {{ ansible_env.PWD }}/roles/common/files/
  sudo: yes
