# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
WORKSPACE_PATH = "~/Dropbox/workspace/webstream-framework/"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "webstream-test" do |node|
    node.vm.box = "bento/centos-7.4"
    node.vm.hostname = "webstream-test"
    node.vm.network :public_network, ip: "192.168.0.218", bridge: "en1: Wi-Fi (AirPort)"
    node.vm.network :forwarded_port, guest: 22, host: 2252, id: "ssh"
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 2048]
  end

  config.vm.synced_folder "../../setup", "/vagrant",
    type: "rsync",
    owner: "vagrant",
    group: "vagrant"

  config.vm.synced_folder WORKSPACE_PATH + "Test", "/workspace/webstream-framework/Test",
    type: "rsync",
    owner: "vagrant",
    group: "vagrant",
    rsync__exclude: [".git/", "sandbox/", "vendor/", "TestApp/vendor/", "TestApp/core/", "TestApp/log/"]

  config.vm.synced_folder WORKSPACE_PATH + "WebStream", "/workspace/webstream-framework/Test/TestApp/core",
    type: "rsync",
    owner: "vagrant",
    group: "vagrant",
    rsync__exclude: [".git/", "sandbox/"]

  ["IO", "Container" ,"Log", "Cache", "DI", "Annotation", "Exception", "ClassLoader", "Database"].each do |repository|
      config.vm.synced_folder WORKSPACE_PATH + repository, "/workspace/webstream-framework/" + repository,
        type: "rsync",
        owner: "vagrant",
        group: "vagrant",
        rsync__exclude: [".git/", "composer.lock", "sandbox/", "vendor/"]
  end

  config.vm.provision :ansible_local do |ansible|
    ansible.playbook = "setup.yml"
  end

  config.ssh.pty = true
end
