repo_uri: git://github.com/webstream-framework/WebStream.git
branch: feature-0.4
dest_path: "{{ wwwroot }}/webstream-framework/WebStream"
test_log_path: /core/WebStream/Test/Sample/log
test_view_cache_path: /core/WebStream/Test/Sample/app/views/_cache
test_static_file_path: /core/WebStream/Test/Sample/app/views/_public
