# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # host
  config.vm.define "host" do |node|
    node.vm.box = "chef/centos-6.5"
    node.vm.hostname = "webstream-host"
    node.vm.network :public_network, ip: "192.168.0.202"
    node.vm.network :forwarded_port, guest: 22, host: 2223
  end

  # web
  config.vm.define "web" do |node|
    node.vm.box = "chef/centos-6.5"
    node.vm.hostname = "webstream-web"
    node.vm.network :public_network, ip: "192.168.0.203"
    node.vm.network :forwarded_port, guest: 22, host: 2224
  end

  # db
  config.vm.define "db" do |node|
    node.vm.box = "chef/centos-6.5"
    node.vm.hostname = "webstream-db"
    node.vm.network :public_network, ip: "192.168.0.204"
    node.vm.network :forwarded_port, guest: 22, host: 2225
  end
end
