- name: docker run (data only container)
  shell: "{{ item.shell }}"
  with_items:
    - { shell: docker run -itd -v /mnt/docker/mysql --name php70_data_mysql docker/data }
    - { shell: docker run -itd -v /mnt/docker/postgres --name php70_data_postgres docker/data }
    - { shell: docker run -itd -v /mnt/docker/sqlite --name php70_data_sqlite docker/data }
    - { shell: docker run -itd -v /mnt/docker/apache/www --name php70_data_apache docker/data }
  sudo: yes
- name: docker run (database)
  shell: "{{ item.shell }}"
  with_items:
    - { shell: 'docker run -itd --privileged --volumes-from php70_data_mysql --name php70_webstream-mysql docker/mysql /sbin/init' }
    - { shell: 'docker run -itd --privileged --volumes-from php70_data_postgres --name php70_webstream-postgres docker/postgres /sbin/init' }
    - { shell: 'docker run -itd --privileged --volumes-from php70_data_sqlite --name php70_webstream-sqlite docker/sqlite /sbin/init' }
  sudo: yes
- name: copy ansible files to container (mysql)
  shell: tar -cv * | sudo docker exec -i php70_webstream-mysql tar x -C /root/ansible chdir=mysql/ansible
- name: copy ansible files to container (postgres)
  shell: tar -cv * | sudo docker exec -i php70_webstream-postgres tar x -C /root/ansible chdir=postgres/ansible
- name: copy ansible files to container (sqlite)
  shell: tar -cv * | sudo docker exec -i php70_webstream-sqlite tar x -C /root/ansible chdir=sqlite/ansible
- name: docker provision (database)
  shell: "{{ item.shell }}"
  with_items:
    - { shell: 'docker exec -t php70_webstream-mysql ansible-playbook -i "localhost," /root/ansible/settings.yml' }
    - { shell: 'docker exec -t php70_webstream-postgres ansible-playbook -i "localhost," /root/ansible/settings.yml' }
    - { shell: 'docker exec -t php70_webstream-sqlite ansible-playbook -i "localhost," /root/ansible/settings.yml' }
  sudo: yes
