- name: set yum repository
  yum: name={{ item }}
  with_items:
    - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
- include: setup-php5.4.yml
  tags:
    - php5.4
- include: setup-php5.5.yml
  tags:
    - php5.5
- include: setup-php5.6.yml
  tags:
    - php5.6
- name: php.ini settings
  lineinfile: >-
    dest=/etc/php.ini
    regexp='^;date.timezone'
    line="date.timezone = Asia/Tokyo"
    state=present
- name: install composer
  shell: /usr/bin/curl -s http://getcomposer.org/installer | php && mv -f composer.phar /usr/bin/composer
