- name: install php
  yum: pkg={{ item }} state=latest enablerepo=remi,remi-php56
  with_items:
    - php
    - php-devel
    - php-mbstring
    - php-mysql
    - php-pgsql
    - php-pdo
    - php-xml
    - php-pecl-xdebug
