# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  settings = {}
  settings[:ipaddr] = "192.168.0.31"
  settings[:port] = 2261
  settings[:workspace_path] = "~/Dropbox/workspace/webstream-framework/"

  config.vm.define "webstream-dev" do |node|
    node.vm.box = "bento/centos-7.4"
    node.vm.hostname = "webstream-dev"
    node.vm.network :public_network, ip: settings[:ipaddr], bridge: "en1: Wi-Fi (AirPort)"
    node.vm.network :forwarded_port, guest: 22, host: settings[:port], id: "ssh"
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 2048]
  end

  config.vm.synced_folder "setup", "/vagrant",
    type: "rsync",
    owner: "vagrant",
    group: "vagrant"

  ["IO", "Container" ,"Log", "Cache", "DI", "Annotation", "Exception", "ClassLoader", "Database"].each do |repository|
    config.vm.synced_folder settings[:workspace_path] + repository, "/workspace/webstream-framework/apps/" + repository,
      type: "rsync",
      owner: "vagrant",
      group: "vagrant",
      rsync__exclude: [".git/", "sandbox/", "vendor/", "composer.lock"]
  end

  config.vm.synced_folder settings[:workspace_path] + "infrastructure/dev/docker/settings", "/workspace/webstream-framework/infrastructure/",
    type: "rsync",
    owner: "vagrant",
    group: "vagrant",
    rsync__exclude: [".git/", "sandbox/", "vendor/"]

  config.vm.synced_folder settings[:workspace_path] + "WebStream", "/workspace/webstream-framework/apps/WebStream",
    type: "rsync",
    owner: "vagrant",
    group: "vagrant",
    rsync__exclude: [".git/", "sandbox/", "vendor/",
      settings[:workspace_path] + "WebStream/test/Application/log/"]

  config.vm.provision :ansible_local do |ansible|
    ansible.compatibility_mode = '2.0'
    ansible.playbook = "setup.yml"
  end

  config.ssh.pty = true
end
